name: Merge Develop to Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge develop -> release
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: release
          github_token: ${{ secrets.ADMIN_ACTION_RIGHTS }}
